version: "3.8"

services:
  adminer:
    image: adminer
    ports:
      - 8888:8080
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=bridge-network"
    networks:
      - bridge-network

  db:
    image: mariadb:10.7.4-focal
    environment:
      MYSQL_ROOT_PASSWORD: YourPasswordHere
    volumes:
      - db:/var/lib/mysql
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=bridge-network"
    networks:
      - bridge-network

  backend:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile.dev
    working_dir: /app
    volumes:
      - .:/app
      - bundle_cache:/bundle
    environment:
      DATABASE_POOL: 5
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: YourPasswordHere
      REDIS_URL: redis://redis:6379/0
      BUNDLE_PATH: /bundle
      RAILS_ENV: development
      PORT: 3000
      #
      KOALA_ACCESS_TOKEN: ''
      KOALA_APP_ACCESS_TOKEN: ''
      KOALA_APP_SECRET: ''
      KOALA_APP_ID: ''
    command: /bin/sh ".dockerdev/commander/rails.sh"
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=bridge-network"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # 
      - "traefik.http.routers.backend-http.rule=Host(`ghiencham.com`)"
      - "traefik.http.routers.backend-http.entrypoints=web"
      - "traefik.http.routers.backend-http.middlewares=redirect-to-https@docker"
      #
      - "traefik.http.services.backend-service.loadbalancer.server.port=3000"
      # 
      - "traefik.http.routers.backend-secured.rule=Host(`ghiencham.com`)"
      - "traefik.http.routers.backend-secured.entrypoints=websecured"
      - "traefik.http.routers.backend-secured.tls.certresolver=myhttpchallenge"
    depends_on:
      - db
      - redis
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge

volumes:
  db:
  bundle_cache:
